server:
  port: 9191
kafka:
  ipAddress: localhost:9092
controller:
  base : /api/v1
  education : /education
  location : /location
  skills : /skills
  project : /project
  experience : /experience
  certificate : /certificate
  interest : /interest
