logging:
  file: logs/apring-boot-logging.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.stackroute: DEBUG
    org.hibernate: ERROR
    log4j.logger.org.thymeleaf: DEBUG

controller:
  base: /api/v1/registration
  user: /user
kafka:
  ipAddress: 172.23.239.245:9092

server:
  port: 8086