server:
  port: 8087
kafka:
  ipAddress: 172.23.239.245:9092
  groupId: group_id12
  outputTopic: indexer
  linsteningTopic: experience
  containerFactory: userKafkaListenerFactory
  relationshipProperty: Working
  relationshipType: is-a
  operationType: post
  sourceNode: vivek
  sourceNodeProperties: pandey
  terminalNode: Bangalore
  terminalNodeProperties: Visiting