server:
  port: 8082

spring:
  application:
      name: EducationService
  cloud:
       config:
           uri: http://localhost:8888

management:
  security:
    enabled: false
eureka:         #tells about the Eureka server details and its refresh time
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5


kafka:
  ipAddress: 172.23.239.245:9092
  groupId: group_id20
  outputTopic: indexer
  linsteningTopic: education
  containerFactory: userKafkaListenerFactory